In [7]:
import numpy as np
marks=np.array([88,56,78,90,83])
marks+5
mark= marks-5
marks/2
marks>=60
print(marks)

[88 56 78 90 83]


In [12]:
marks = [36,89,65,49,90]
marks[0]
marks[-1]
marks[:]
marks[1:4]

[89, 65, 49]

In [13]:
marks = np.array([
    [89,90,67],
    [80,67,49],
    [96,84,79]]
    )
print(marks)

[[89 90 67]
 [80 67 49]
 [96 84 79]]


In [ ]:
marks[0][2]   #indexing
marks[0:2][0:2]  #slicing

array([[89, 90, 67],
       [80, 67, 49]])

In [ ]:
marks[1:,0]     

array([80, 96])

In [17]:
marks[1:,0]
print(marks[1:],[0])

[[80 67 49]
 [96 84 79]] [0]


In [ ]:
import numpy as np
b1 = np.array([56,78,90])
b2 = np.array([89,90,67])
comb = np.concatenate((b1,b2))
comb

array([56, 78, 90, 89, 90, 67])

In [7]:
print(np.split(comb,2),sep = ",")

[array([56, 78, 90]), array([89, 90, 67])]


In [9]:
print(np.split(comb,2))
for arr in np.split(comb,3):
    print(arr)

[array([56, 78, 90]), array([89, 90, 67])]
[56 78]
[90 89]
[90 67]


In [ ]:
b1 = np.array([                            #Axis 0 ----> x --> Row 
    [56,78,89],                               #Axis 1 ---> Y --> Column
    [34,45,67]]
    )
b2 = np.array([
    [90,87,69],
    [29,35,50]]
    )
comb1 = np.concatenate((b1,b2),axis=1)
print(comb1)
print("-----------")
comb0 = np.concatenate((b1,b2),axis=0)
comb0

[[56 78 89 90 87 69]
 [34 45 67 29 35 50]]
-----------


array([[56, 78, 89],
       [34, 45, 67],
       [90, 87, 69],
       [29, 35, 50]])

In [15]:
mark = np.array([
[89,67,90],
[92,83,85],
[98,56,43]
])
print(np.where(mark==85))
print(mark)

(array([1]), array([2]))
[[89 67 90]
 [92 83 85]
 [98 56 43]]


In [18]:

np.where(mark>=80) # gives indexes
print(mark[np.where(mark>=80)]) # gives exact values
print(mark)

[89 90 92 83 85 98]
[[89 67 90]
 [92 83 85]
 [98 56 43]]


In [8]:
mark = np.array([
[89,67,90],
[92,83,85],
[98,56,43]
])
np.sort(mark)
np.sort(mark,axis=1)
np.sort(mark,axis=0)
print(np.sort(mark)[::-1])
# print(mark)

[[43 56 98]
 [83 85 92]
 [67 89 90]]
